[package]
name = "http-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
hyper = { workspace = true }
http-body-util = { workspace = true }
hyper-util = { workspace = true }
